{
    "name": "Tameson Sale Customizations",
    "version": "13.0.0.1.0.0",
    "description": """
    Tameson Sale Customizations.
    """,
    "author": "Tameson",
    "depends": [
        "sale",
        "tameson_product",
        "tameson_contact",
        "delivery",
        "account",
        "sale_automatic_workflow",
        "sale_financial_risk",
    ],
    "data": [
        "security/ir.model.access.csv",
        # "data/cron.xml",
        "data/layout.xml",
        "wizard/reshipment.xml",
        "views/sale_views.xml",
        # "report/report_invoice.xml",
        # "report/report_sale_order.xml",
        "report/report_external_layout.xml",
        # "data/report_layout.xml",
        # "wizard/base_document_layout_views.xml",
        "views/res_country_view.xml",
        # "views/partner.xml",
        "wizard/product_creation.xml",
        "views/stock.xml",
        "views/pricelist.xml",
        "views/payment_terms.xml",
    ],
    "application": False,
    "license": "OPL-1",
}
